export const WHITE = '#EFEFEF'
export const RED = '#CC1E23'
export const BLUE = '#0A1321'
export const DARKBLUE = '#000606'
export const storageKeyName = 'csfl.cz/session-token'
export const DARK = '#000A0A'
export const LIGHT = '#EFEFEF'